name: metalink_flutter
description: Flutter UI components for link previews using the MetaLink package
version: 2.0.0
repository: https://github.com/omar-hanafy/metalink_flutter
topics:
  - link-preview
  - link-detector
  - url
  - link
  - metadata

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_helper_utils: ">=7.0.1 <9.0.0"
  hive_ce_flutter: ^2.3.4
  http: ^1.6.0
  metalink: ^2.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

screenshots:
  - description: 'Card styles link preview'
    path: screenshots/1.png
  - description: 'URL detection preview'
    path: screenshots/2.png
  - description: 'Controller usage preview'
    path: screenshots/3.png
  - description: 'Custom styles link preview'
    path: screenshots/4.png
